vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /Uploads/products/Articles
            upload_destination: '%kernel.project_dir%/public/Uploads/products/Articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true